[strava]
client_id = "12345"
client_secret = "secret"
# optional refresh token obtained via authorization
refresh_token = ""
token_path = "./token.json"      # cached access token and expiry
                                   # `cargo run --bin authorize` writes here

[storage]
data_dir = "./data"
download_count = 10
user = "athlete1"
