name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Run tests
        env:
          RUSTFLAGS: "-C link-arg=-Wl,--no-keep-memory"
          RUST_BACKTRACE: full
        run: cargo test --locked --all-targets -- --test-threads=1
